/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	scheme "github.com/gardener/machine-controller-manager/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// YandexMachineClassesGetter has a method to return a YandexMachineClassInterface.
// A group's client should implement this interface.
type YandexMachineClassesGetter interface {
	YandexMachineClasses(namespace string) YandexMachineClassInterface
}

// YandexMachineClassInterface has methods to work with YandexMachineClass resources.
type YandexMachineClassInterface interface {
	Create(*machine.YandexMachineClass) (*machine.YandexMachineClass, error)
	Update(*machine.YandexMachineClass) (*machine.YandexMachineClass, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*machine.YandexMachineClass, error)
	List(opts v1.ListOptions) (*machine.YandexMachineClassList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.YandexMachineClass, err error)
	YandexMachineClassExpansion
}

// yandexMachineClasses implements YandexMachineClassInterface
type yandexMachineClasses struct {
	client rest.Interface
	ns     string
}

// newYandexMachineClasses returns a YandexMachineClasses
func newYandexMachineClasses(c *MachineClient, namespace string) *yandexMachineClasses {
	return &yandexMachineClasses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the yandexMachineClass, and returns the corresponding yandexMachineClass object, and an error if there is any.
func (c *yandexMachineClasses) Get(name string, options v1.GetOptions) (result *machine.YandexMachineClass, err error) {
	result = &machine.YandexMachineClass{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of YandexMachineClasses that match those selectors.
func (c *yandexMachineClasses) List(opts v1.ListOptions) (result *machine.YandexMachineClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &machine.YandexMachineClassList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested yandexMachineClasses.
func (c *yandexMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a yandexMachineClass and creates it.  Returns the server's representation of the yandexMachineClass, and an error, if there is any.
func (c *yandexMachineClasses) Create(yandexMachineClass *machine.YandexMachineClass) (result *machine.YandexMachineClass, err error) {
	result = &machine.YandexMachineClass{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		Body(yandexMachineClass).
		Do().
		Into(result)
	return
}

// Update takes the representation of a yandexMachineClass and updates it. Returns the server's representation of the yandexMachineClass, and an error, if there is any.
func (c *yandexMachineClasses) Update(yandexMachineClass *machine.YandexMachineClass) (result *machine.YandexMachineClass, err error) {
	result = &machine.YandexMachineClass{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		Name(yandexMachineClass.Name).
		Body(yandexMachineClass).
		Do().
		Into(result)
	return
}

// Delete takes name of the yandexMachineClass and deletes it. Returns an error if one occurs.
func (c *yandexMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *yandexMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched yandexMachineClass.
func (c *yandexMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.YandexMachineClass, err error) {
	result = &machine.YandexMachineClass{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("yandexmachineclasses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
