/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
	scheme "github.com/gardener/machine-controller-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VsphereMachineClassesGetter has a method to return a VsphereMachineClassInterface.
// A group's client should implement this interface.
type VsphereMachineClassesGetter interface {
	VsphereMachineClasses(namespace string) VsphereMachineClassInterface
}

// VsphereMachineClassInterface has methods to work with VsphereMachineClass resources.
type VsphereMachineClassInterface interface {
	Create(*v1alpha1.VsphereMachineClass) (*v1alpha1.VsphereMachineClass, error)
	Update(*v1alpha1.VsphereMachineClass) (*v1alpha1.VsphereMachineClass, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VsphereMachineClass, error)
	List(opts v1.ListOptions) (*v1alpha1.VsphereMachineClassList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VsphereMachineClass, err error)
	VsphereMachineClassExpansion
}

// vsphereMachineClasses implements VsphereMachineClassInterface
type vsphereMachineClasses struct {
	client rest.Interface
	ns     string
}

// newVsphereMachineClasses returns a VsphereMachineClasses
func newVsphereMachineClasses(c *MachineV1alpha1Client, namespace string) *vsphereMachineClasses {
	return &vsphereMachineClasses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vsphereMachineClass, and returns the corresponding vsphereMachineClass object, and an error if there is any.
func (c *vsphereMachineClasses) Get(name string, options v1.GetOptions) (result *v1alpha1.VsphereMachineClass, err error) {
	result = &v1alpha1.VsphereMachineClass{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VsphereMachineClasses that match those selectors.
func (c *vsphereMachineClasses) List(opts v1.ListOptions) (result *v1alpha1.VsphereMachineClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VsphereMachineClassList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vsphereMachineClasses.
func (c *vsphereMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vsphereMachineClass and creates it.  Returns the server's representation of the vsphereMachineClass, and an error, if there is any.
func (c *vsphereMachineClasses) Create(vsphereMachineClass *v1alpha1.VsphereMachineClass) (result *v1alpha1.VsphereMachineClass, err error) {
	result = &v1alpha1.VsphereMachineClass{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		Body(vsphereMachineClass).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vsphereMachineClass and updates it. Returns the server's representation of the vsphereMachineClass, and an error, if there is any.
func (c *vsphereMachineClasses) Update(vsphereMachineClass *v1alpha1.VsphereMachineClass) (result *v1alpha1.VsphereMachineClass, err error) {
	result = &v1alpha1.VsphereMachineClass{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		Name(vsphereMachineClass.Name).
		Body(vsphereMachineClass).
		Do().
		Into(result)
	return
}

// Delete takes name of the vsphereMachineClass and deletes it. Returns an error if one occurs.
func (c *vsphereMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vsphereMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vsphereMachineClass.
func (c *vsphereMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VsphereMachineClass, err error) {
	result = &v1alpha1.VsphereMachineClass{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vspheremachineclasses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
