/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVsphereMachineClasses implements VsphereMachineClassInterface
type FakeVsphereMachineClasses struct {
	Fake *FakeMachine
	ns   string
}

var vspheremachineclassesResource = schema.GroupVersionResource{Group: "machine.sapcloud.io", Version: "", Resource: "vspheremachineclasses"}

var vspheremachineclassesKind = schema.GroupVersionKind{Group: "machine.sapcloud.io", Version: "", Kind: "VsphereMachineClass"}

// Get takes name of the vsphereMachineClass, and returns the corresponding vsphereMachineClass object, and an error if there is any.
func (c *FakeVsphereMachineClasses) Get(name string, options v1.GetOptions) (result *machine.VsphereMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vspheremachineclassesResource, c.ns, name), &machine.VsphereMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.VsphereMachineClass), err
}

// List takes label and field selectors, and returns the list of VsphereMachineClasses that match those selectors.
func (c *FakeVsphereMachineClasses) List(opts v1.ListOptions) (result *machine.VsphereMachineClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vspheremachineclassesResource, vspheremachineclassesKind, c.ns, opts), &machine.VsphereMachineClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &machine.VsphereMachineClassList{ListMeta: obj.(*machine.VsphereMachineClassList).ListMeta}
	for _, item := range obj.(*machine.VsphereMachineClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vsphereMachineClasses.
func (c *FakeVsphereMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vspheremachineclassesResource, c.ns, opts))

}

// Create takes the representation of a vsphereMachineClass and creates it.  Returns the server's representation of the vsphereMachineClass, and an error, if there is any.
func (c *FakeVsphereMachineClasses) Create(vsphereMachineClass *machine.VsphereMachineClass) (result *machine.VsphereMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vspheremachineclassesResource, c.ns, vsphereMachineClass), &machine.VsphereMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.VsphereMachineClass), err
}

// Update takes the representation of a vsphereMachineClass and updates it. Returns the server's representation of the vsphereMachineClass, and an error, if there is any.
func (c *FakeVsphereMachineClasses) Update(vsphereMachineClass *machine.VsphereMachineClass) (result *machine.VsphereMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vspheremachineclassesResource, c.ns, vsphereMachineClass), &machine.VsphereMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.VsphereMachineClass), err
}

// Delete takes name of the vsphereMachineClass and deletes it. Returns an error if one occurs.
func (c *FakeVsphereMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vspheremachineclassesResource, c.ns, name), &machine.VsphereMachineClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVsphereMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vspheremachineclassesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &machine.VsphereMachineClassList{})
	return err
}

// Patch applies the patch and returns the patched vsphereMachineClass.
func (c *FakeVsphereMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.VsphereMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vspheremachineclassesResource, c.ns, name, pt, data, subresources...), &machine.VsphereMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.VsphereMachineClass), err
}
