/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYandexMachineClasses implements YandexMachineClassInterface
type FakeYandexMachineClasses struct {
	Fake *FakeMachine
	ns   string
}

var yandexmachineclassesResource = schema.GroupVersionResource{Group: "machine.sapcloud.io", Version: "", Resource: "yandexmachineclasses"}

var yandexmachineclassesKind = schema.GroupVersionKind{Group: "machine.sapcloud.io", Version: "", Kind: "YandexMachineClass"}

// Get takes name of the yandexMachineClass, and returns the corresponding yandexMachineClass object, and an error if there is any.
func (c *FakeYandexMachineClasses) Get(name string, options v1.GetOptions) (result *machine.YandexMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(yandexmachineclassesResource, c.ns, name), &machine.YandexMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.YandexMachineClass), err
}

// List takes label and field selectors, and returns the list of YandexMachineClasses that match those selectors.
func (c *FakeYandexMachineClasses) List(opts v1.ListOptions) (result *machine.YandexMachineClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(yandexmachineclassesResource, yandexmachineclassesKind, c.ns, opts), &machine.YandexMachineClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &machine.YandexMachineClassList{ListMeta: obj.(*machine.YandexMachineClassList).ListMeta}
	for _, item := range obj.(*machine.YandexMachineClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yandexMachineClasses.
func (c *FakeYandexMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(yandexmachineclassesResource, c.ns, opts))

}

// Create takes the representation of a yandexMachineClass and creates it.  Returns the server's representation of the yandexMachineClass, and an error, if there is any.
func (c *FakeYandexMachineClasses) Create(yandexMachineClass *machine.YandexMachineClass) (result *machine.YandexMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(yandexmachineclassesResource, c.ns, yandexMachineClass), &machine.YandexMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.YandexMachineClass), err
}

// Update takes the representation of a yandexMachineClass and updates it. Returns the server's representation of the yandexMachineClass, and an error, if there is any.
func (c *FakeYandexMachineClasses) Update(yandexMachineClass *machine.YandexMachineClass) (result *machine.YandexMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(yandexmachineclassesResource, c.ns, yandexMachineClass), &machine.YandexMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.YandexMachineClass), err
}

// Delete takes name of the yandexMachineClass and deletes it. Returns an error if one occurs.
func (c *FakeYandexMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(yandexmachineclassesResource, c.ns, name), &machine.YandexMachineClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYandexMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(yandexmachineclassesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &machine.YandexMachineClassList{})
	return err
}

// Patch applies the patch and returns the patched yandexMachineClass.
func (c *FakeYandexMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.YandexMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(yandexmachineclassesResource, c.ns, name, pt, data, subresources...), &machine.YandexMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.YandexMachineClass), err
}
